# Stage 1: Build the application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the application
FROM node:20-alpine
WORKDIR /app

# Copy built assets and necessary files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json .

# Install production dependencies
RUN npm install --omit=dev

EXPOSE 5175
ENV PORT=5175

# Start the application using node
CMD ["node", "build"]
